@host = http://localhost:5000

@id = 8394d0a3-90a9-45f9-a04d-c42a89d4e3eb

GET {{host}}/receipt/{{id}}
Accept: application/json
Content-Type: application/json

###

POST {{host}}/receipt/qr
Accept: application/json
Content-Type: application/json

{
  "qr" : "t=20200924T1837&s=349.93&fn=9282440300682838&i=46534&fp=1273019065&n=1"
}

